# Generated by Django 5.2.13 on 2026-05-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='loader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loading',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
