# Generated by Django 5.2.13 on 2026-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_loading_loader_alter_loading_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AlterField(
            model_name='loading',
            name='material',
            field=models.CharField(choices=[('sand', 'Sand'), ('stones', 'Stones'), ('gravel', 'Gravel')], max_length=20),
        ),
    ]
