# Generated by Django 5.2.13 on 2026-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_delete_material_alter_loading_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loading',
            name='material',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
