# Generated by Django 5.2.13 on 2026-05-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_loading_material'),
        ('trucks', '0002_alter_truck_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck')),
            ],
        ),
    ]
