# Generated by Django 5.2.13 on 2026-05-03 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_truckarrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loading',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='truckarrival',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('arrived', 'Arrived')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loading',
            name='loader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'loader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loading',
            name='material',
            field=models.CharField(default='sand', max_length=50),
        ),
        migrations.AlterField(
            model_name='truckarrival',
            name='material',
            field=models.CharField(default='sand', max_length=50),
        ),
    ]
